name: Generate Art

on:
  schedule:
    - cron: '0 0 * * *' # æ¯å¤©è¿è¡Œ
  workflow_dispatch:

permissions:
  contents: write

jobs:
  paint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Generate Image
      run: python main.py
      
    - name: Commit Art
      run: |
        git config --global user.email "huangshu007@outlook.com"
        git config --global user.name "huc-b2"
        
        # æ·»åŠ æ–°ç”Ÿæˆçš„å›¾ç‰‡å’Œ README
        git add gallery/ README.md
        
        git commit -m "ğŸ¨ Generate art: $(date +'%Y-%m-%d')"
        git push
